[package]
name = "sea-orm-migration-ex-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = { version = "0.1.57" }
sea-orm-migration = { version = "0.9.1" }
