[package]
name = "sea_orm_migration_ex_macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
sea_orm_migration_ex_core = { path = "../core" }
syn = { version = "1.0.99" }
